<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Naresh" name="ClassWorkMaven.TestNG.HRMTestNGAssertHard" tests="3" failures="1" timestamp="2019-12-14T17:48:59 IST" time="9.691" errors="0">
  <testcase name="signIn" time="2.642" classname="ClassWorkMaven.TestNG.HRMTestNGAssertHard">
    <failure type="java.lang.AssertionError" message="True-Welcome Admin logged in expected [No Welcome Admin] but found [Welcome Admin]">
      <![CDATA[java.lang.AssertionError: True-Welcome Admin logged in expected [No Welcome Admin] but found [Welcome Admin]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at ClassWorkMaven.TestNG.HRMTestNGAssertHard.signIn(HRMTestNGAssertHard.java:47)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:51)
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:41)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- signIn -->
  <testcase name="userSearch" time="2.559" classname="ClassWorkMaven.TestNG.HRMTestNGAssertHard"/>
  <testcase name="userSignOut" time="4.490" classname="ClassWorkMaven.TestNG.HRMTestNGAssertHard"/>
</testsuite> <!-- ClassWorkMaven.TestNG.HRMTestNGAssertHard -->
